In [1]:
# Using Python
# Option 1: pydytuesday python library
## pip install pydytuesday

import pydytuesday
import pandas as pd

# Download files from the week, which you can then read in locally
pydytuesday.get_date('2025-11-25')

# Option 2: Read directly from GitHub and assign to an object

spi_indicators = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-11-25/spi_indicators.csv')

Trying to fetch README from: https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2025/2025-11-25/readme.md
Successfully fetched README from: https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2025/2025-11-25/readme.md
Downloading map.png...
Successfully saved map.png to c:\Users\Dell\Documents\Códigos\data-analysis-process\Aprendizado-de-maquina-job\map.png
Downloading meta.yaml...
Successfully saved meta.yaml to c:\Users\Dell\Documents\Códigos\data-analysis-process\Aprendizado-de-maquina-job\meta.yaml
Downloading spi_indicators.csv...
Successfully saved spi_indicators.csv to c:\Users\Dell\Documents\Códigos\data-analysis-process\Aprendizado-de-maquina-job\spi_indicators.csv

In [2]:
spi_indicators

,iso3c,country,region,income,year,population,overall_score,data_use_score,data_services_score,data_products_score,data_sources_score,data_infrastructure_score
0,DNK,Denmark,Europe & Central Asia,High income,2023,5946952,95.255833,100.0,98.466667,90.71250,87.100,100.0
1,FIN,Finland,Europe & Central Asia,High income,2023,5584264,95.115417,100.0,96.433333,90.96875,88.175,100.0
2,POL,Poland,Europe & Central Asia,High income,2023,36685849,94.653750,100.0,97.300000,84.54375,91.425,100.0
3,SWE,Sweden,Europe & Central Asia,High income,2023,10536632,94.410000,100.0,96.000000,90.57500,85.475,100.0
4,ESP,Spain,Europe & Central Asia,High income,2023,48373336,94.325000,100.0,91.200000,92.62500,87.800,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4335,VIR,Virgin Islands (U.S.),Latin America & Caribbean,High income,2004,108466,NaN,0.0,NaN,NaN,NaN,NaN
4336,PSE,West Bank and Gaza,Middle East & North Africa,Lower middle income,2004,3236626,NaN,20.0,NaN,NaN,NaN,NaN
4337,YEM,"Yemen, Rep.",Middle East & North Africa,Low income,2004,20733406,NaN,20.0,NaN,NaN,NaN,NaN
4338,ZMB,Zambia,Sub-Saharan Africa,Lower middle income,2004,11188040,NaN,40.0,NaN,NaN,NaN,NaN
4339,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,2004,12160881,NaN,20.0,NaN,NaN,NaN,NaN

In [5]:
spi_indicators[spi_indicators['country'] == 'Brazil']

,iso3c,country,region,income,year,population,overall_score,data_use_score,data_services_score,data_products_score,data_sources_score,data_infrastructure_score
59,BRA,Brazil,Latin America & Caribbean,Upper middle income,2023,216422446,80.639167,83.4,87.333333,77.28750,85.175000,70.0
273,BRA,Brazil,Latin America & Caribbean,Upper middle income,2022,215313498,81.080417,90.0,87.333333,72.89375,85.175000,70.0
491,BRA,Brazil,Latin America & Caribbean,Upper middle income,2021,214326223,81.212917,90.0,87.000000,80.15625,78.908333,70.0
701,BRA,Brazil,Latin America & Caribbean,Upper middle income,2020,213196304,79.170833,90.0,87.000000,74.11250,74.741667,70.0
909,BRA,Brazil,Latin America & Caribbean,Upper middle income,2019,211782878,79.257083,90.0,83.300000,73.09375,74.891667,75.0
1130,BRA,Brazil,Latin America & Caribbean,Upper middle income,2018,210166592,77.613333,90.0,83.300000,76.57500,73.191667,65.0
1349,BRA,Brazil,Latin America & Caribbean,Upper middle income,2017,208504960,74.246667,90.0,79.466667,76.17500,70.591667,55.0
1560,BRA,Brazil,Latin America & Caribbean,Upper middle income,2016,206859578,74.277083,90.0,80.600000,74.84375,70.941667,55.0
1762,BRA,Brazil,Latin America & Caribbean,Upper middle income,2015,205188205,NaN,70.0,NaN,73.54375,68.191667,NaN
1979,BRA,Brazil,Latin America & Caribbean,Upper middle income,2014,203459650,NaN,50.0,NaN,77.28750,NaN,NaN
2196,BRA,Brazil,Latin America & Caribbean,Upper middle income,2013,201721767,NaN,50.0,NaN,79.18125,NaN,NaN
2413,BRA,Brazil,Latin America & Caribbean,Upper middle income,2012,199977707,NaN,50.0,NaN,79.74375,NaN,NaN
2630,BRA,Brazil,Latin America & Caribbean,Upper middle income,2011,198185302,NaN,50.0,NaN,77.31250,NaN,NaN
2847,BRA,Brazil,Latin America & Caribbean,Upper middle income,2010,196353492,NaN,50.0,NaN,75.35625,NaN,NaN
3064,BRA,Brazil,Latin America & Caribbean,Upper middle income,2009,194517549,NaN,40.0,NaN,78.97500,NaN,NaN
3281,BRA,Brazil,Latin America & Caribbean,Upper middle income,2008,192672317,NaN,40.0,NaN,75.86875,NaN,NaN
3498,BRA,Brazil,Latin America & Caribbean,Upper middle income,2007,190779453,NaN,40.0,NaN,76.21875,NaN,NaN
3715,BRA,Brazil,Latin America & Caribbean,Upper middle income,2006,188820682,NaN,40.0,NaN,74.59375,NaN,NaN
3932,BRA,Brazil,Latin America & Caribbean,Upper middle income,2005,186797334,NaN,40.0,NaN,73.99375,NaN,NaN
4149,BRA,Brazil,Latin America & Caribbean,Upper middle income,2004,184722043,NaN,40.0,NaN,NaN,NaN,NaN

## Preparação de Dados

Preparação para 3 modelos, sendo eles:
- Random Forest
- Regressão Logística
- SVM

## Random Forest

Necessário:
- Sem escalonamento
- Encoding One-hot ou Ordinal
- Tratamento de Outliers leve
- Suposição linear: Não

In [21]:
random_forest_data = spi_indicators.copy()
random_forest_data = random_forest_data[random_forest_data['income'] != 'Not classified']
random_forest_data.describe()

,year,population,overall_score,data_use_score,data_services_score,data_products_score,data_sources_score,data_infrastructure_score
count,4320.000000,4.320000e+03,1417.000000,4320.000000,1428.000000,4066.000000,1551.000000,1511.000000
mean,2013.500000,3.340240e+07,65.052884,50.740741,64.850187,55.198148,51.982855,55.102581
std,5.766949,1.324528e+08,17.501637,29.522559,23.503276,18.724464,20.076224,28.213461
min,2004.000000,9.791000e+03,11.769583,0.000000,0.333333,4.893750,0.000000,0.000000
25%,2008.750000,7.298842e+05,53.153333,30.000000,56.233333,45.462500,37.200000,30.000000
50%,2013.500000,5.854352e+06,64.706250,40.000000,64.033333,58.006250,53.241667,50.000000
75%,2018.250000,2.124189e+07,80.322500,80.000000,86.466667,68.448438,68.725000,80.000000
max,2023.000000,1.428628e+09,95.255833,100.000000,100.000000,94.312500,94.175000,100.000000

In [4]:
random_forest_data.columns

Index(['iso3c', 'country', 'region', 'income', 'year', 'population',
       'overall_score', 'data_use_score', 'data_services_score',
       'data_products_score', 'data_sources_score',
       'data_infrastructure_score'],
      dtype='str')

In [22]:
X = random_forest_data.drop(columns=['income', 'iso3c', 'country'])
y = random_forest_data['income']

In [23]:
random_forest_data.dtypes

iso3c                            str
country                          str
region                           str
income                           str
year                           int64
population                     int64
overall_score                float64
data_use_score               float64
data_services_score          float64
data_products_score          float64
data_sources_score           float64
data_infrastructure_score    float64
dtype: object

In [25]:
# Definindo quem é numérico e quem é categórico pelo que sobrou
numeric_features = [
    'year', 'population', 'overall_score', 'data_use_score', 
    'data_services_score', 'data_products_score', 
    'data_sources_score', 'data_infrastructure_score'
]
categorical_features = ['region']

In [14]:
import matplotlib.pyplot as plt

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

numeric_transformer_rf = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')) # Usa a mediana para não ser afetado por outliers da população
])

categorical_transformer_rf = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor_rf = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer_rf, numeric_features),
        ('cat', categorical_transformer_rf, categorical_features)
    ])

# 4. Crie o Pipeline final (Exemplo com SVM)
clf_rf = Pipeline(steps=[('preprocessor', preprocessor_rf)])

## SVM e Regressão Logística

Necessário:
- Escalonamento
- Encoding One-hot ou Ordinal
- Tratamento de Outliers Pesado
- Suposição linear: Sim

In [29]:

numeric_transformer_linear = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()) # <-- CRÍTICO AQUI
])

categorical_transformer_linear = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    # drop='first' remove a primeira coluna gerada para evitar multicolinearidade (ótimo para LogReg)
    ('encoder', OneHotEncoder(handle_unknown='ignore', drop='first')) 
])

preprocessor_linear = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer_linear, numeric_features),
        ('cat', categorical_transformer_linear, categorical_features)
    ])

In [30]:
clf_svm_log = Pipeline(steps=[('preprocessor', preprocessor_linear)])

## Exportação

In [31]:
import joblib

In [33]:
joblib.dump(clf_rf, 'clfs/process_random_forest_spi.pkl')
joblib.dump(clf_svm_log, 'clfs/process_svm_log.pkl')

['clfs/process_svm_log.pkl']